package report

import (
	"CloudOracle/internal/shared"
	"fmt"
	"time"

	"codeberg.org/go-pdf/fpdf"
)

func GeneratePDF(findings []shared.Finding, aiSummary string, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Arial", "I", 8)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(0, 10, fmt.Sprintf("Generated by CloudOracle - Page %d/{nb}", pdf.PageNo()),
			"", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")
	pdf.AddPage()

	// HEADER
	pdf.SetFont("Arial", "B", 24)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(0, 12, "CloudOracle Report")
	pdf.Ln(14)

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(120, 120, 120)
	pdf.Cell(0, 6, fmt.Sprintf("Generated on %s", time.Now().Format("January 2, 2006 15:04 MST")))
	pdf.Ln(10)

	// SUMMARY
	var totalSavings, totalCost float64
	severityCounts := map[shared.Severity]int{}

	for _, f := range findings {
		totalSavings += f.MonthlySavings
		totalCost += f.MonthlyCost
		severityCounts[f.Severity]++
	}

	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(0, 8, "Executive Summary")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 11)
	pdf.SetTextColor(60, 60, 60)
	pdf.Cell(0, 6, fmt.Sprintf("Total findings: %d", len(findings)))
	pdf.Ln(6)
	pdf.Cell(0, 6, fmt.Sprintf("Current monthly cost analyzed: $%.2f", totalCost))
	pdf.Ln(6)

	pdf.SetFont("Arial", "B", 11)
	pdf.SetTextColor(40, 140, 60)
	pdf.Cell(0, 6, fmt.Sprintf("Potential monthly savings: $%.2f", totalSavings))
	pdf.Ln(6)
	pdf.Cell(0, 6, fmt.Sprintf("Potential annual savings: $%.2f", totalSavings*12))
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 11)
	pdf.SetTextColor(60, 60, 60)
	pdf.Cell(0, 6, fmt.Sprintf("Severity: %d HIGH, %d MEDIUM, %d LOW",
		severityCounts[shared.SeverityHigh],
		severityCounts[shared.SeverityMedium],
		severityCounts[shared.SeverityLow]))
	pdf.Ln(12)

	// === AI EXECUTIVE SUMMARY (if available) ===
	if aiSummary != "" {
		pdf.SetFont("Arial", "B", 14)
		pdf.SetTextColor(30, 30, 30)
		pdf.Cell(0, 8, "AI Analysis")
		pdf.Ln(8)

		pdf.SetFont("Arial", "", 10)
		pdf.SetTextColor(60, 60, 60)
		pdf.MultiCell(0, 5, aiSummary, "", "L", false)
		pdf.Ln(8)
	}

	// === DETAILED FINDINGS TABLE ===
	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(0, 8, "Detailed Findings")
	pdf.Ln(10)

	// Table header row
	drawTableHeader(pdf)

	// Table data rows
	pdf.SetFont("Arial", "", 8)
	for _, f := range findings {
		// Page break if running out of space
		if pdf.GetY() > 270 {
			pdf.AddPage()
			drawTableHeader(pdf)
			pdf.SetFont("Arial", "", 8)
		}

		// Background color by severity
		switch f.Severity {
		case shared.SeverityHigh:
			pdf.SetFillColor(255, 235, 235)
		case shared.SeverityMedium:
			pdf.SetFillColor(255, 250, 230)
		case shared.SeverityLow:
			pdf.SetFillColor(235, 250, 235)
		}

		pdf.SetTextColor(50, 50, 50)
		pdf.CellFormat(18, 6, string(f.Severity), "1", 0, "C", true, 0, "")
		pdf.CellFormat(40, 6, truncate(f.ResourceID, 18), "1", 0, "L", true, 0, "")
		pdf.CellFormat(20, 6, f.Service, "1", 0, "C", true, 0, "")
		pdf.CellFormat(32, 6, truncate(f.ResourceType, 14), "1", 0, "L", true, 0, "")
		pdf.CellFormat(30, 6, fmt.Sprintf("$%.2f", f.MonthlyCost), "1", 0, "R", true, 0, "")

		// Savings in green to make them pop
		pdf.SetTextColor(40, 140, 60)
		pdf.CellFormat(40, 6, fmt.Sprintf("$%.2f", f.MonthlySavings), "1", 0, "R", true, 0, "")
		pdf.Ln(6)
	}

	// === RECOMMENDED ACTIONS ===
	pdf.Ln(8)

	if pdf.GetY() > 240 {
		pdf.AddPage()
	}

	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(0, 8, "Recommended Actions")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 9)
	for i, f := range findings {
		if pdf.GetY() > 260 {
			pdf.AddPage()
		}

		pdf.SetFont("Arial", "B", 10)
		pdf.SetTextColor(30, 30, 30)
		title := fmt.Sprintf("%d. [%s] %s (%s) - Save $%.2f/month",
			i+1,
			string(f.Severity),
			f.ResourceID,
			f.ResourceType,
			f.MonthlySavings,
		)
		pdf.MultiCell(0, 5, title, "", "L", false)

		// Issue description
		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(80, 80, 80)
		pdf.MultiCell(0, 5, "Issue: "+f.Description, "", "L", false)

		pdf.SetTextColor(40, 110, 50)
		pdf.MultiCell(0, 5, "Action: "+f.Recommendation, "", "L", false)

		pdf.Ln(3)
	}
	if err := pdf.OutputFileAndClose(outputPath); err != nil {
		return fmt.Errorf("error writing PDF: %w", err)
	}
	return nil
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

func drawTableHeader(pdf *fpdf.Fpdf) {
	pdf.SetFillColor(50, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Arial", "B", 9)
	pdf.CellFormat(18, 7, "Severity", "1", 0, "C", true, 0, "")
	pdf.CellFormat(40, 7, "Resource ID", "1", 0, "L", true, 0, "")
	pdf.CellFormat(20, 7, "Service", "1", 0, "C", true, 0, "")
	pdf.CellFormat(32, 7, "Type", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 7, "Cost/mo", "1", 0, "R", true, 0, "")
	pdf.CellFormat(40, 7, "Savings/mo", "1", 0, "R", true, 0, "")
	pdf.Ln(7)
}
