// Package diff aggregates per-resource cost estimates from internal/pricing
// into a plan-wide picture. The output (CostDiff) is consumed by the Markdown
// renderer in milestone 14.2 and the LLM narrative layer in milestone 15.
//
// This package does NOT call the AWS Pricing API directly — it delegates to
// pricing.EstimateChange via an injected estimator. The split lets analysis
// logic (sorting, categorising, top-movers, notes) be tested without a Source
// or fixture JSON.
package diff

import (
	"context"

	"CloudOracle/internal/pricing"
)

// CostDiff is the aggregate cost impact of a single Terraform plan.
//
// Changes contains one entry per resource_change in the plan, including
// changes that could not be priced (those carry Skipped=true). Changes is
// sorted by absolute MonthlyDelta descending, so the most impactful items
// surface first; Skipped items have delta=0 and naturally sort last.
//
// Created, Deleted, Updated, Replaced, and Skipped are non-overlapping
// subsets of Changes (with one nuance: items with Skipped=true never
// appear in the action-keyed slices regardless of their Action — even an
// unsupported aws_iam_role with action=create lands in Skipped only).
// All five subsets share the same descending-by-abs-delta order as Changes.
//
// TopMovers is the leading slice of Changes (length min(TopMoversCount,
// non-skipped count)) used by the renderer for the "biggest changes"
// summary at the top of a PR comment. Skipped items are excluded from
// TopMovers because their delta of 0 carries no signal.
//
// Confidence is the weakest non-skipped confidence across Changes (low
// dominates medium dominates high). With no non-skipped changes, the
// default is ConfidenceHigh — there is nothing to be unsure about.
//
// Notes are plan-wide observations generated by Analyze itself, not
// inherited from individual ChangeEstimates: skip-count summaries, net
// direction of the plan, "no priceable resources" diagnostics, etc.
type CostDiff struct {
	TotalMonthlyDelta float64
	Currency          string

	Changes []pricing.ChangeEstimate

	Created  []pricing.ChangeEstimate
	Deleted  []pricing.ChangeEstimate
	Updated  []pricing.ChangeEstimate
	Replaced []pricing.ChangeEstimate
	Skipped  []pricing.ChangeEstimate

	TopMovers []pricing.ChangeEstimate

	Confidence pricing.Confidence

	Notes []string

	Stats Stats
}

// Stats holds counts by category for quick summary rendering. The values
// form a disjoint partition of the plan: every change is counted in
// exactly one of {Created, Deleted, Updated, Replaced, NoOp, Skipped},
// so Total = Created + Deleted + Updated + Replaced + NoOp + Skipped.
//
// NoOp counts no-op AND read actions (both have zero cost impact and no
// real "change" to price). Skipped counts the items that ended up in the
// Skipped slice MINUS those NoOp items — i.e. only the changes we
// genuinely could not price (unsupported types, data sources,
// estimation failures). Priced is a convenience alias for Created +
// Deleted + Updated + Replaced.
type Stats struct {
	Total    int
	Created  int
	Deleted  int
	Updated  int
	Replaced int
	NoOp     int
	Skipped  int
	Priced   int
}

// Source is anything that can serve raw Pricing API products. Both
// *pricing.Client (live calls) and *pricing.Cache (disk-cached) satisfy
// it. Defining the interface here — rather than importing pricing's
// unexported productGetter — keeps the diff package decoupled from the
// pricing package's internal types.
type Source interface {
	GetProducts(ctx context.Context, serviceCode string, filters map[string]string) ([]string, error)
}
